# Generated by Django 3.0.8 on 2020-09-12 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='admin',
            field=models.BooleanField(default=False, verbose_name='admin'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.TextField(default='user profile goes here', max_length=1000, verbose_name='biography'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='founder',
            field=models.BooleanField(default=False, verbose_name='founder'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.URLField(default='https://via.placeholder.com/300.jpg', verbose_name='profile photo'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='location',
            field=models.CharField(default='Home Town', max_length=100, verbose_name='location'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='newsletter_signup',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(default=61400000000, max_length=13, verbose_name='phone number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='supporter',
            field=models.BooleanField(default=False, verbose_name='supporter'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='terms_privacy',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(max_length=80, verbose_name='password'),
        ),
    ]
