# Generated by Django 3.0.8 on 2020-09-12 09:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200912_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='created on'),
        ),
    ]
