# Generated by Django 3.0.8 on 2020-09-27 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200926_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='created_on',
            field=models.DateTimeField(verbose_name='created on'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='founder',
            field=models.BooleanField(verbose_name='founder'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(verbose_name='admin'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='newsletter_signup',
            field=models.BooleanField(verbose_name='subscribe to newsletter'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='supporter',
            field=models.BooleanField(verbose_name='supporter'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='terms_privacy',
            field=models.BooleanField(verbose_name='accept Terms & Privacy'),
        ),
    ]
