# Generated by Django 3.0.8 on 2020-09-09 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_pledge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='description',
        ),
        migrations.RemoveField(
            model_name='project',
            name='goal',
        ),
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
        migrations.RemoveField(
            model_name='project',
            name='title',
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('Facilities', 'Facilities'), ('Resources', 'Resources'), ('Exposure', 'Exposure'), ('Expertise', 'Expertise')], default='Expertise', max_length=20, verbose_name='needs'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_faq',
            field=models.TextField(default='A list of FAQ goes here.', max_length=5000, verbose_name='FAQ'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_goal',
            field=models.IntegerField(default=12, verbose_name='project goal'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_image',
            field=models.URLField(default='https://via.placeholder.com/300.jpg', verbose_name='project image'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_intro',
            field=models.TextField(default='A brief intro to the Project goes here.', max_length=500, verbose_name='introduction'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_name',
            field=models.CharField(default='New Project', max_length=100, verbose_name='project'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_stage',
            field=models.CharField(choices=[('Start', 'Start'), ('Trial', 'Trial'), ('Adjust', 'Adjust'), ('Retail', 'Retail')], default='Start', max_length=10, verbose_name='stage'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_story',
            field=models.TextField(default='The project owners background story goes here.', max_length=5000, verbose_name='story'),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_created',
            field=models.DateTimeField(verbose_name='project commenced'),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_open',
            field=models.BooleanField(verbose_name='project status'),
        ),
        migrations.AlterField(
            model_name='project',
            name='owner',
            field=models.CharField(max_length=100),
        ),
    ]
