# Generated by Django 3.0.8 on 2020-09-09 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20200909_2056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pledge',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='pledge',
            name='quantity',
        ),
        migrations.AddField(
            model_name='pledge',
            name='is_fulfilled',
            field=models.BooleanField(default=False, verbose_name='promise fulfilled'),
        ),
        migrations.AddField(
            model_name='pledge',
            name='pledge_description',
            field=models.CharField(default='All the details about what is being promised to be given do here.', max_length=200, verbose_name='description of pledge'),
        ),
        migrations.AddField(
            model_name='pledge',
            name='pledge_quantity',
            field=models.IntegerField(default=1, verbose_name='amount pledged'),
        ),
        migrations.AddField(
            model_name='pledge',
            name='terms_privacy',
            field=models.BooleanField(default=True, verbose_name='accept Terms and Privacy'),
        ),
        migrations.AlterField(
            model_name='pledge',
            name='anonymous',
            field=models.BooleanField(verbose_name='maintain privacy'),
        ),
        migrations.AlterField(
            model_name='pledge',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pledges', to='projects.Project', verbose_name='project'),
        ),
        migrations.AlterField(
            model_name='pledge',
            name='supporter',
            field=models.CharField(default='Someone Wonderful', max_length=100, verbose_name='pledge made by'),
        ),
    ]
