# Generated by Django 3.0.8 on 2020-09-09 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20200909_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_content', models.TextField(max_length=5000, verbose_name='project update')),
                ('update_date', models.DateTimeField(verbose_name='updated on')),
                ('update_author', models.CharField(max_length=100)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='projects.Project', verbose_name='project')),
            ],
        ),
    ]
