# Generated by Django 3.0.8 on 2020-09-12 01:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0007_auto_20200912_1037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='update',
            old_name='update_author',
            new_name='owner',
        ),
        migrations.RemoveField(
            model_name='pledge',
            name='supporter',
        ),
        migrations.AddField(
            model_name='pledge',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pledge_supporter', to=settings.AUTH_USER_MODEL, verbose_name='supporter'),
            preserve_default=False,
        ),
    ]
