# Generated by Django 3.0.8 on 2020-09-14 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_auto_20200912_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pledge',
            name='is_fulfilled',
            field=models.BooleanField(default=False, verbose_name='pledge fulfilled'),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='project commenced'),
        ),
    ]
