# Generated by Django 3.0.8 on 2020-09-15 22:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0011_auto_20200914_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='date_amended',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='project last amended'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pledge',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pledges', to='projects.Project', verbose_name='project pledges'),
        ),
        migrations.AlterField(
            model_name='update',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='update_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='update',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='projects.Project', verbose_name='project updates'),
        ),
        migrations.AlterField(
            model_name='update',
            name='update_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='updated on'),
        ),
    ]
