# Generated by Django 3.0.8 on 2020-09-17 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_auto_20200916_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pledge',
            name='anonymous',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='pledge',
            name='is_fulfilled',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='pledge',
            name='pledge_description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='pledge',
            name='pledge_quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pledge',
            name='terms_privacy',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_amended',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_open',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_faq',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_goal',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_image',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_intro',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_stage',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_story',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='update',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='projects.Project'),
        ),
        migrations.AlterField(
            model_name='update',
            name='update_content',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='update',
            name='update_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
