# Generated by Django 3.0.8 on 2020-09-22 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_remove_project_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(default='Expertise', max_length=20),
            preserve_default=False,
        ),
    ]
