# Generated by Django 3.0.8 on 2020-09-22 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_project_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='update_name',
            field=models.CharField(default='Update Title', max_length=100),
            preserve_default=False,
        ),
    ]
