# Generated by Django 3.0.8 on 2020-09-22 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_update_update_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pledge_outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pledge_outcome', to='projects.Pledge', verbose_name='pledge outcome')),
                ('project_outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_outcome', to='projects.Project', verbose_name='project outcomes')),
            ],
        ),
    ]
