# Generated by Django 3.0.8 on 2020-09-23 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_outcome'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Outcome',
        ),
    ]
