# Generated by Django 3.0.8 on 2020-10-18 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_auto_20200926_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_needs',
            field=models.TextField(default='More specific details about the needs goes here', max_length=5000),
            preserve_default=False,
        ),
    ]
